import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'FeedsModel.dart';
import 'Users.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'Posts.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'Posts.g.dart';





@freezed
class Posts with _$Posts  {
  const factory Posts({
    required String postUid,
    required String postedBy,
    required String postCaptions,
    required String? postImage,
    required String userName,
    required String userImage,
    required List<Users> postsTags,
    required String postTime,
    required String? postIpAddress,
    required List<String> likes
  }) = _Posts;

  factory Posts.fromJson(Map<String, dynamic> json)
  => _$PostsFromJson(json);
}