import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

import 'FeedsModel.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'Users.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'Users.g.dart';

@freezed
class Users with _$Users  {
  const factory Users({
    required String userUid,
    required String userName,
    required String userEmail,
    required String userMobile,
    required List<FeedsModel> userPost,
    required String? userIpAddress,
  }) = _Users;

  factory Users.fromJson(Map<String, dynamic> json)
  => _$UsersFromJson(json);
}